env:
  - GHCVER=7.8.3

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-1.20 ghc-$GHCVER-prof ghc-$GHCVER-dyn
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.20/bin:$PATH
 - export PATH=~/.cabal/bin:$PATH
 - cabal update

script:
  - cabal configure -v2  # -v2 provides useful information for debugging
  - cabal build

install:
 - 'cabal sandbox init'
 - cabal install -j . --only-dependencies --reorder-goals --max-backjumps=-1

